---
include:
  - board: xiao_ble
    shield: roBa_R
    snippet: studio-rpc-usb-uart
    cmake-args: "-DZMK_EXTRA_MODULES=$GITHUB_WORKSPACE;$GITHUB_WORKSPACE/zmk-pmw3610-driver"
    artifact-name: roBa_R

  - board: xiao_ble
    shield: roBa_L
    artifact-name: roBa_L

  - board: xiao_ble
    shield: settings_reset
    artifact-name: settings_reset
